# serializers.py
# -------------------------------------------------------
# WHAT IS THIS FILE?
# A serializer is a TRANSLATOR.
#
# Your database stores Python objects (User, Post, Comment).
# But the outside world (Postman, browsers, apps) speaks JSON.
#
# The serializer converts:
#   Python object  →  JSON   (when SENDING data out)
#   JSON           →  Python (when RECEIVING data in)
#
# Example:
#   Python: User(username="Kirk", email="kirk@email.com")
#   JSON:   {"username": "Kirk", "email": "kirk@email.com"}
# -------------------------------------------------------

from rest_framework import serializers
from .models import User, Post, Comment


class UserSerializer(serializers.ModelSerializer):
    class Meta:
        model = User  # Which model are we translating?
        fields = ['id', 'username', 'email', 'created_at']
        # fields = which pieces of data to include in the JSON response
        # 'id' is auto-generated by Django for every record


class PostSerializer(serializers.ModelSerializer):
    # This adds a read-only field that shows the author's username
    # instead of just showing the author's ID number.
    # So instead of {"author": 1}, you get {"author": "Kirk"}
    author_username = serializers.CharField(source='author.username', read_only=True)

    class Meta:
        model = Post
        fields = ['id', 'author', 'author_username', 'content', 'created_at']

    def validate_author(self, value):
        # VALIDATION: Before saving, check that the author actually exists.
        # If someone sends author ID 999 but no user #999 exists, reject it.
        if not User.objects.filter(id=value.id).exists():
            raise serializers.ValidationError("Author does not exist.")
        return value


class CommentSerializer(serializers.ModelSerializer):
    author_username = serializers.CharField(source='author.username', read_only=True)

    class Meta:
        model = Comment
        fields = ['id', 'post', 'author', 'author_username', 'content', 'created_at']
